; Experimental non-PA T3-S3 LR1121, one radio, 2.4 GHz bench setup.
[env:Murmur_LilyGO_T3S3_LR1121_TX_via_UART]
extends = env:Unified_ESP32S3_LR1121_TX_via_UART
board_upload.flash_size = 4MB
build_flags =
	${env:Unified_ESP32S3_LR1121_TX_via_ETX.build_flags}
	-DMURMUR_ENCRYPT
	-DRegulatory_Domain_FCC_915
	-DRegulatory_Domain_EU_CE_2400
extra_scripts =
	${env_common_esp32.extra_scripts}
	python/lilygo_bench.py

[env:Murmur_LilyGO_T3S3_LR1121_RX_via_UART]
extends = env:Unified_ESP32S3_LR1121_RX_via_UART
board_upload.flash_size = 4MB
build_flags =
	${env:Unified_ESP32S3_LR1121_RX_via_UART.build_flags}
	-DMURMUR_ENCRYPT
	-DRegulatory_Domain_FCC_915
	-DRegulatory_Domain_EU_CE_2400
extra_scripts =
	${env_common_esp32.extra_scripts}
	python/lilygo_bench.py
